{"ast":null,"code":"import { withScope, captureException, showReportDialog } from '@sentry/browser';\nimport { logger } from '@sentry/utils';\nimport hoistNonReactStatics from 'hoist-non-react-statics';\nimport * as React from 'react';\nvar _jsxFileName = \"/home/runner/work/sentry-javascript/sentry-javascript/packages/react/src/errorboundary.tsx\";\n\nfunction isAtLeastReact17(version) {\n  var major = version.match(/^([^.]+)/);\n  return major !== null && parseInt(major[0]) >= 17;\n}\n\nvar UNKNOWN_COMPONENT = 'unknown';\nvar INITIAL_STATE = {\n  componentStack: null,\n  error: null,\n  eventId: null\n};\n/**\n * A ErrorBoundary component that logs errors to Sentry. Requires React >= 16.\n * NOTE: If you are a Sentry user, and you are seeing this stack frame, it means the\n * Sentry React SDK ErrorBoundary caught an error invoking your application code. This\n * is expected behavior and NOT indicative of a bug with the Sentry React SDK.\n */\n\nclass ErrorBoundary extends React.Component {\n  constructor() {\n    super(...arguments);\n\n    ErrorBoundary.prototype.__init.call(this);\n\n    ErrorBoundary.prototype.__init2.call(this);\n  }\n\n  __init() {\n    this.state = INITIAL_STATE;\n  }\n\n  componentDidCatch(error, _ref) {\n    let {\n      componentStack\n    } = _ref;\n    const {\n      beforeCapture,\n      onError,\n      showDialog,\n      dialogOptions\n    } = this.props;\n    withScope(scope => {\n      // If on React version >= 17, create stack trace from componentStack param and links\n      // to to the original error using `error.cause` otherwise relies on error param for stacktrace.\n      // Linking errors requires the `LinkedErrors` integration be enabled.\n      if (isAtLeastReact17(React.version)) {\n        var errorBoundaryError = new Error(error.message);\n        errorBoundaryError.name = `React ErrorBoundary ${errorBoundaryError.name}`;\n        errorBoundaryError.stack = componentStack; // Using the `LinkedErrors` integration to link the errors together.\n\n        error.cause = errorBoundaryError;\n      }\n\n      if (beforeCapture) {\n        beforeCapture(scope, error, componentStack);\n      }\n\n      var eventId = captureException(error, {\n        contexts: {\n          react: {\n            componentStack\n          }\n        }\n      });\n\n      if (onError) {\n        onError(error, componentStack, eventId);\n      }\n\n      if (showDialog) {\n        showReportDialog({ ...dialogOptions,\n          eventId\n        });\n      } // componentDidCatch is used over getDerivedStateFromError\n      // so that componentStack is accessible through state.\n\n\n      this.setState({\n        error,\n        componentStack,\n        eventId\n      });\n    });\n  }\n\n  componentDidMount() {\n    const {\n      onMount\n    } = this.props;\n\n    if (onMount) {\n      onMount();\n    }\n  }\n\n  componentWillUnmount() {\n    const {\n      error,\n      componentStack,\n      eventId\n    } = this.state;\n    const {\n      onUnmount\n    } = this.props;\n\n    if (onUnmount) {\n      onUnmount(error, componentStack, eventId);\n    }\n  }\n\n  __init2() {\n    this.resetErrorBoundary = () => {\n      const {\n        onReset\n      } = this.props;\n      const {\n        error,\n        componentStack,\n        eventId\n      } = this.state;\n\n      if (onReset) {\n        onReset(error, componentStack, eventId);\n      }\n\n      this.setState(INITIAL_STATE);\n    };\n  }\n\n  render() {\n    const {\n      fallback,\n      children\n    } = this.props;\n    const {\n      error,\n      componentStack,\n      eventId\n    } = this.state;\n\n    if (error) {\n      let element = undefined;\n\n      if (typeof fallback === 'function') {\n        element = fallback({\n          error,\n          componentStack,\n          resetError: this.resetErrorBoundary,\n          eventId\n        });\n      } else {\n        element = fallback;\n      }\n\n      if (React.isValidElement(element)) {\n        return element;\n      }\n\n      if (fallback) {\n        (typeof __SENTRY_DEBUG__ === 'undefined' || __SENTRY_DEBUG__) && logger.warn('fallback did not produce a valid ReactElement');\n      } // Fail gracefully if no fallback provided or is not valid\n\n\n      return null;\n    }\n\n    if (typeof children === 'function') {\n      return children();\n    }\n\n    return children;\n  }\n\n}\n\nfunction withErrorBoundary(WrappedComponent, errorBoundaryOptions) {\n  var componentDisplayName = WrappedComponent.displayName || WrappedComponent.name || UNKNOWN_COMPONENT;\n\n  var Wrapped = props => React.createElement(ErrorBoundary, { ...errorBoundaryOptions,\n    __self: this,\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 168\n    }\n  }, React.createElement(WrappedComponent, { ...props,\n    __self: this,\n    __source: {\n      fileName: _jsxFileName,\n      lineNumber: 169\n    }\n  }));\n\n  Wrapped.displayName = `errorBoundary(${componentDisplayName})`; // Copy over static methods from Wrapped component to Profiler HOC\n  // See: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over\n\n  hoistNonReactStatics(Wrapped, WrappedComponent);\n  return Wrapped;\n}\n\nexport { ErrorBoundary, UNKNOWN_COMPONENT, isAtLeastReact17, withErrorBoundary }; //# sourceMappingURL=errorboundary.js.map","map":null,"metadata":{},"sourceType":"module"}